### ISSUE TITLE
UDTFs must start with Column arguments.

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#131]
Consider the following UDTFs (from test_omnisci_column_basic.py)
```
@omnisci('int32(Column<double>, double, int32, int64|sizer=RowMultiplier,'
             'OutputColumn<double>)')
def my_row_copier_mul_param1(x, alpha, beta, m, y):
        ...

@omnisci('int32(double, Column<double>, int32, int64|sizer=RowMultiplier,'
         'OutputColumn<double>)')
def my_row_copier_mul_param2(alpha, x, beta, m, y):
        ...
```

The test with `my_row_copier_mul_param1` works while `my_row_copier_mul_param2` fails with:

<details>

```
2020-07-15 16:17:26 ERROR CalciteServerHandler:process:184 - Validation: java.lang.NullPointerException
org.apache.calcite.tools.ValidationException: java.lang.NullPointerException
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:219)
	at com.mapd.calcite.parser.MapDParser.convertSqlToRelNode(MapDParser.java:782)
	at com.mapd.calcite.parser.MapDParser.processSql(MapDParser.java:397)
	at com.mapd.calcite.parser.MapDParser.process(MapDParser.java:370)
	at com.mapd.parser.server.CalciteServerHandler.process(CalciteServerHandler.java:180)
	at com.omnisci.thrift.calciteserver.CalciteServer$Processor$process.getResult(CalciteServer.java:713)
	at com.omnisci.thrift.calciteserver.CalciteServer$Processor$process.getResult(CalciteServer.java:692)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.setValidatedNodeType(SqlValidatorImpl.java:1737)
	at org.apache.calcite.sql.SqlOperator.validateOperands(SqlOperator.java:454)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:321)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:218)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5864)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5851)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1800)
	at org.apache.calcite.sql.validate.ProcedureNamespace.validateImpl(ProcedureNamespace.java:53)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1110)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1084)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3256)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3238)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3510)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1110)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1084)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:232)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1059)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:766)
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:217)
	... 12 more
2020-07-15 16:17:26 ERROR CalciteServerHandler:process:217 - Exception occurred: java.lang.NullPointerException
org.apache.calcite.tools.ValidationException: java.lang.NullPointerException
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:219)
	at com.mapd.calcite.parser.MapDParser.convertSqlToRelNode(MapDParser.java:782)
	at com.mapd.calcite.parser.MapDParser.processSql(MapDParser.java:397)
	at com.mapd.calcite.parser.MapDParser.process(MapDParser.java:370)
	at com.mapd.parser.server.CalciteServerHandler.process(CalciteServerHandler.java:180)
	at com.omnisci.thrift.calciteserver.CalciteServer$Processor$process.getResult(CalciteServer.java:713)
	at com.omnisci.thrift.calciteserver.CalciteServer$Processor$process.getResult(CalciteServer.java:692)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.setValidatedNodeType(SqlValidatorImpl.java:1737)
	at org.apache.calcite.sql.SqlOperator.validateOperands(SqlOperator.java:454)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:321)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:218)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5864)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5851)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1800)
	at org.apache.calcite.sql.validate.ProcedureNamespace.validateImpl(ProcedureNamespace.java:53)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1110)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1084)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3256)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3238)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3510)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1110)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1084)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:232)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1059)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:766)
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:217)
	... 12 more
2020-07-15T16:17:26.468754 E 6792 DBHandler.cpp:1138 Exception: query failed from broken view or other schema related issue

```

</details>

**Comment by pearu** [comment]
Resolved by https://github.com/omnisci/omniscidb-internal/pull/4754
