### ISSUE TITLE
test_redefine randomly crashes rbc on omniscidb server v5.4 when CUDA is enabled

### ISSUE THREAD

**Issue by guilhermeleobas** [xnd-project/rbc#136]
As title. 

```
rbc/tests/test_omnisci.py::test_redefine FAILED

Traceback (most recent call last):
  File "/home/guilhermel/miniconda3/envs/rbc/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/config/__init__.py", line 124, in main
    ret = config.hook.pytest_cmdline_main(
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/main.py", line 228, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/terminal.py", line 717, in pytest_sessionfinish
    outcome.get_result()
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/runner.py", line 80, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/runner.py", line 335, in teardown_all
    self._pop_and_teardown()
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/runner.py", line 310, in _pop_and_teardown
    self._teardown_with_finalization(colitem)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/runner.py", line 328, in _teardown_with_finalization
    self._callfinalizers(colitem)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/runner.py", line 325, in _callfinalizers
    raise exc
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/runner.py", line 318, in _callfinalizers
    fin()
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/fixtures.py", line 878, in finish
    raise exc
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/fixtures.py", line 871, in finish
    func()
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/_pytest/fixtures.py", line 800, in _teardown_yield_fixture
    next(it)
  File "/work/guilhermel/git/rbc/rbc/tests/test_omnisci.py", line 86, in omnisci
    m.sql_execute('DROP TABLE IF EXISTS {table_name}'.format(**locals()))
  File "/work/guilhermel/git/rbc/rbc/omniscidb.py", line 262, in sql_execute
    result = self.thrift_call(
  File "/work/guilhermel/git/rbc/rbc/omniscidb.py", line 255, in thrift_call
    return client(Omnisci={name: args})['Omnisci'][name]
  File "/work/guilhermel/git/rbc/rbc/thrift/client.py", line 196, in __call__
    r = mth(*query_args)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/thriftpy2/thrift.py", line 219, in _req
    return self._recv(_api)
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/thriftpy2/thrift.py", line 231, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy2/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin
  File "thriftpy2/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32
  File "thriftpy2/transport/buffered/cybuffered.pyx", line 65, in thriftpy2.transport.buffered.cybuffered.TCyBufferedTransport.c_read
  File "thriftpy2/transport/buffered/cybuffered.pyx", line 69, in thriftpy2.transport.buffered.cybuffered.TCyBufferedTransport.read_trans
  File "thriftpy2/transport/cybase.pyx", line 61, in thriftpy2.transport.cybase.TCyBuffer.read_trans
  File "/home/guilhermel/miniconda3/envs/rbc/lib/python3.8/site-packages/thriftpy2/transport/socket.py", line 110, in read
    buff = self.sock.recv(sz)
socket.timeout: timed out
```

**Comment by guilhermeleobas** [comment]
xref #135

**Comment by pearu** [comment]
I am going to enable this test as local testing shows that when a CUDA enabled omniscidb server has been warmed up (it can be take up to a minute from a fresh build), the test always succeeds.
