### ISSUE TITLE
Printing a decorated function with `RemoteOmnisci` causes an `AttributeError`

### ISSUE THREAD

**Issue by tupui** [xnd-project/rbc#404]
There is a defect in the `__repr__` of `RemoteJIT`.

```python
>>> from rbc.omniscidb import RemoteOmnisci
>>> omni = RemoteOmnisci()
>>> def farenheight2celcius(f):
...     return (f - 32)* 5 / 9
...
>>> omni('double(double)')(farenheight2celcius)
```
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tupui/rbc/rbc/remotejit.py", line 323, in __repr__
    self.signature, self.local)
  File "/home/tupui/rbc/rbc/remotejit.py", line 319, in local
    return Caller(self.func, self.signature.local)
  File "/home/tupui/rbc/rbc/remotejit.py", line 113, in local
    sig = Signature(self.remotejit.local)
  File "/home/tupui/rbc/rbc/remotejit.py", line 458, in local
    localjit = type(self)(local=True, debug=self.debug)
  File "/home/tupui/rbc/rbc/omniscidb.py", line 277, in __init__
    self._init_thrift_typemap()
  File "/home/tupui/rbc/rbc/omniscidb.py", line 288, in _init_thrift_typemap
    for typename, typ in self.thrift_client.thrift.__dict__.items():
AttributeError: 'LocalClient' object has no attribute 'thrift'
```

**Comment by tupui** [comment]
It's actually a problem with the `LocalClient`:

```python
>>> from rbc.omniscidb import RemoteOmnisci
>>> omni = RemoteOmnisci(local=True)
```
```python-stacktrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tupui/Documents/Quansight/Projects/Omnisci/rbc/rbc/omniscidb.py", line 277, in __init__
    self._init_thrift_typemap()
  File "/Users/tupui/Documents/Quansight/Projects/Omnisci/rbc/rbc/omniscidb.py", line 288, in _init_thrift_typemap
    for typename, typ in self.thrift_client.thrift.__dict__.items():
AttributeError: 'LocalClient' object has no attribute 'thrift'
```
