### ISSUE TITLE
test_numpy_function[arcsin] crashes omniscidb server when CUDA enabled

### ISSUE THREAD

**Issue by pearu** [xnd-project/rbc#59]
```
2020-04-14T11:29:49.926462 F 29925 NvidiaKernel.cpp:83 Check failed: cuLinkComplete(link_state, &cubin, &cubinSize) == CUDA_SUCCESS (999 == 0) 
Aborted (core dumped)
```

**Comment by pearu** [comment]
A complete list of numpy functions that cause the same error:
```
'arcsin', 'arccos', 'arctan', 'arctan2', 'hypot', 'sinh', 'cosh',
'tanh', 'arcsinh', 'arccosh', 'arctanh', 'expm1', 'exp2', 'log2',
'log1p', 'logaddexp2'
```

**Comment by pearu** [comment]
When using cuda 10.1, 10.2, 11.0, the gdb output is:

<details>

```
2020-08-10T13:01:14.228763 F 30310 10 NvidiaKernel.cpp:127 Check failed: cuLinkComplete(link_state, &cubin, &cubinSize) == CUDA_SUCCESS (999 == 0) 

Thread 10 "omnisci_server" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffddffb700 (LWP 30322)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffedfbb8b1 in __GI_abort () at abort.c:79
#2  0x00005555565af632 in logger::Logger::~Logger() ()
#3  0x0000555556814362 in ptx_to_cubin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, CudaMgr_Namespace::CudaMgr const*) ()
#4  0x0000555556809f77 in CodeGenerator::generateNativeGPUCode(llvm::Function*, llvm::Function*, std::unordered_set<llvm::Function*, std::hash<llvm::Function*>, std::equal_to<llvm::Function*>, std::allocator<llvm::Function*> > const&, CompilationOptions const&, CodeGenerator::GPUTarget const&) ()
#5  0x000055555680ad12 in Executor::optimizeAndCodegenGPU(llvm::Function*, llvm::Function*, std::unordered_set<llvm::Function*, std::hash<llvm::Function*>, std::equal_to<llvm::Function*>, std::allocator<llvm::Function*> >&, bool, CudaMgr_Namespace::CudaMgr const*, CompilationOptions const&) ()
...
```

</details>

PTX for the GPU:

<details>
'''
//
// Generated by LLVM NVPTX Back-End
//

.version 6.3
.target sm_75
.address_size 64

	// .globl	multifrag_query_hoisted_literals
.extern .func  (.param .b32 func_retval0) pos_start_impl
(
	.param .b64 pos_start_impl_param_0
)
;
.extern .func  (.param .b32 func_retval0) group_buff_idx_impl
()
;
.extern .func  (.param .b32 func_retval0) pos_step_impl
()
;
.extern .func  (.param .b64 func_retval0) init_shared_mem
(
	.param .b64 init_shared_mem_param_0,
	.param .b32 init_shared_mem_param_1
)
;
.extern .func write_back_non_grouped_agg
(
	.param .b64 write_back_non_grouped_agg_param_0,
	.param .b64 write_back_non_grouped_agg_param_1,
	.param .b32 write_back_non_grouped_agg_param_2
)
;
.extern .func  (.param .b64 func_retval0) agg_sum_shared
(
	.param .b64 agg_sum_shared_param_0,
	.param .b64 agg_sum_shared_param_1
)
;
.extern .func sync_threadblock
()
;
.visible .func query_template
(
	.param .b64 query_template_param_0,
	.param .b64 query_template_param_1,
	.param .b64 query_template_param_2,
	.param .b64 query_template_param_3,
	.param .b64 query_template_param_4,
	.param .b64 query_template_param_5,
	.param .b64 query_template_param_6,
	.param .b32 query_template_param_7,
	.param .b64 query_template_param_8,
	.param .b64 query_template_param_9,
	.param .b64 query_template_param_10
)
;
.weak .global .align 8 .u64 _ZN08NumbaEnv13$3cdynamic$3e16$3clambda$3e$242Ed;

.visible .entry multifrag_query_hoisted_literals(
	.param .u64 multifrag_query_hoisted_literals_param_0,
	.param .u64 multifrag_query_hoisted_literals_param_1,
	.param .u64 multifrag_query_hoisted_literals_param_2,
	.param .u64 multifrag_query_hoisted_literals_param_3,
	.param .u64 multifrag_query_hoisted_literals_param_4,
	.param .u64 multifrag_query_hoisted_literals_param_5,
	.param .u64 multifrag_query_hoisted_literals_param_6,
	.param .u64 multifrag_query_hoisted_literals_param_7,
	.param .u64 multifrag_query_hoisted_literals_param_8,
	.param .u64 multifrag_query_hoisted_literals_param_9,
	.param .u64 multifrag_query_hoisted_literals_param_10,
	.param .u64 multifrag_query_hoisted_literals_param_11
)
{
	.reg .pred 	%p<5>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<36>;

	ld.param.u64 	%rd17, [multifrag_query_hoisted_literals_param_1];
	cvta.to.global.u64 	%rd2, %rd17;
	ld.global.u64 	%rd18, [%rd2];
	setp.eq.s64 	%p1, %rd18, 0;
	@%p1 bra 	LBB0_6;
	ld.param.u64 	%rd14, [multifrag_query_hoisted_literals_param_11];
	ld.param.u64 	%rd13, [multifrag_query_hoisted_literals_param_9];
	ld.param.u64 	%rd12, [multifrag_query_hoisted_literals_param_8];
	ld.param.u64 	%rd11, [multifrag_query_hoisted_literals_param_7];
	ld.param.u64 	%rd10, [multifrag_query_hoisted_literals_param_6];
	ld.param.u64 	%rd9, [multifrag_query_hoisted_literals_param_5];
	ld.param.u64 	%rd8, [multifrag_query_hoisted_literals_param_4];
	ld.param.u64 	%rd7, [multifrag_query_hoisted_literals_param_3];
	ld.param.u64 	%rd6, [multifrag_query_hoisted_literals_param_2];
	ld.param.u64 	%rd15, [multifrag_query_hoisted_literals_param_0];
	ld.param.u64 	%rd16, [multifrag_query_hoisted_literals_param_10];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd3, %rd15;
	mov.u64 	%rd35, 0;
	cvta.to.global.u64 	%rd20, %rd35;
	setp.eq.s64 	%p2, %rd3, %rd20;
	@%p2 bra 	LBB0_4;
	mov.u32 	%r14, 1;
LBB0_3:
	add.s32 	%r6, %r14, -1;
	shl.b64 	%rd22, %rd35, 3;
	add.s64 	%rd23, %rd3, %rd22;
	ld.global.u64 	%rd24, [%rd23];
	ld.global.u32 	%r7, [%rd1];
	mul.lo.s32 	%r8, %r7, %r6;
	mul.wide.u32 	%rd25, %r8, 8;
	add.s64 	%rd26, %rd7, %rd25;
	add.s64 	%rd27, %rd8, %rd25;
	{ // callseq 0, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd24;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd6;
	.param .b64 param2;
	st.param.b64 	[param2+0], %rd26;
	.param .b64 param3;
	st.param.b64 	[param3+0], %rd27;
	.param .b64 param4;
	st.param.b64 	[param4+0], %rd9;
	.param .b64 param5;
	st.param.b64 	[param5+0], %rd11;
	.param .b64 param6;
	st.param.b64 	[param6+0], %rd12;
	.param .b32 param7;
	st.param.b32 	[param7+0], %r6;
	.param .b64 param8;
	st.param.b64 	[param8+0], %rd14;
	.param .b64 param9;
	st.param.b64 	[param9+0], %rd10;
	.param .b64 param10;
	st.param.b64 	[param10+0], %rd13;
	call.uni 
	query_template, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6, 
	param7, 
	param8, 
	param9, 
	param10
	);
	} // callseq 0
	cvt.u64.u32 	%rd35, %r14;
	ld.global.u64 	%rd28, [%rd2];
	setp.gt.u64 	%p3, %rd28, %rd35;
	add.s32 	%r14, %r14, 1;
	@%p3 bra 	LBB0_3;
	bra.uni 	LBB0_6;
LBB0_4:
	mov.u32 	%r13, 1;
	mov.u64 	%rd32, 0;
LBB0_5:
	add.s32 	%r10, %r13, -1;
	ld.global.u32 	%r11, [%rd1];
	mul.lo.s32 	%r12, %r11, %r10;
	mul.wide.u32 	%rd29, %r12, 8;
	add.s64 	%rd30, %rd7, %rd29;
	add.s64 	%rd31, %rd8, %rd29;
	{ // callseq 1, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd32;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd6;
	.param .b64 param2;
	st.param.b64 	[param2+0], %rd30;
	.param .b64 param3;
	st.param.b64 	[param3+0], %rd31;
	.param .b64 param4;
	st.param.b64 	[param4+0], %rd9;
	.param .b64 param5;
	st.param.b64 	[param5+0], %rd11;
	.param .b64 param6;
	st.param.b64 	[param6+0], %rd12;
	.param .b32 param7;
	st.param.b32 	[param7+0], %r10;
	.param .b64 param8;
	st.param.b64 	[param8+0], %rd14;
	.param .b64 param9;
	st.param.b64 	[param9+0], %rd10;
	.param .b64 param10;
	st.param.b64 	[param10+0], %rd13;
	call.uni 
	query_template, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6, 
	param7, 
	param8, 
	param9, 
	param10
	);
	} // callseq 1
	cvt.u64.u32 	%rd33, %r13;
	ld.global.u64 	%rd34, [%rd2];
	setp.gt.u64 	%p4, %rd34, %rd33;
	add.s32 	%r13, %r13, 1;
	@%p4 bra 	LBB0_5;
LBB0_6:
	ret;

}
	// .globl	query_template
.visible .func query_template(
	.param .b64 query_template_param_0,
	.param .b64 query_template_param_1,
	.param .b64 query_template_param_2,
	.param .b64 query_template_param_3,
	.param .b64 query_template_param_4,
	.param .b64 query_template_param_5,
	.param .b64 query_template_param_6,
	.param .b32 query_template_param_7,
	.param .b64 query_template_param_8,
	.param .b64 query_template_param_9,
	.param .b64 query_template_param_10
)
{
	.reg .pred 	%p<3>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<22>;

	ld.param.u64 	%rd11, [query_template_param_6];
	ld.param.u64 	%rd12, [query_template_param_5];
	mov.u32 	%r1, 8;
	{ // callseq 2, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd12;
	.param .b32 param1;
	st.param.b32 	[param1+0], %r1;
	.param .b64 retval0;
	call.uni (retval0), 
	init_shared_mem, 
	(
	param0, 
	param1
	);
	ld.param.b64 	%rd13, [retval0+0];
	} // callseq 2
	ld.param.u64 	%rd14, [query_template_param_2];
	ld.u64 	%rd2, [%rd14];
	ld.u64 	%rd21, [%rd12];
	ld.param.u64 	%rd15, [query_template_param_10];
	{ // callseq 3, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd15;
	.param .b32 retval0;
	call.uni (retval0), 
	pos_start_impl, 
	(
	param0
	);
	ld.param.b32 	%r2, [retval0+0];
	} // callseq 3
	{ // callseq 4, 0
	.reg .b32 temp_param_reg;
	.param .b32 retval0;
	call.uni (retval0), 
	group_buff_idx_impl, 
	(
	);
	ld.param.b32 	%r4, [retval0+0];
	} // callseq 4
	cvt.s64.s32 	%rd20, %r2;
	setp.le.s64 	%p1, %rd2, %rd20;
	@%p1 bra 	LBB1_3;
	{ // callseq 5, 0
	.reg .b32 temp_param_reg;
	.param .b32 retval0;
	call.uni (retval0), 
	pos_step_impl, 
	(
	);
	ld.param.b32 	%r6, [retval0+0];
	} // callseq 5
	cvt.s64.s32 	%rd5, %r6;
LBB1_2:
	add.s64 	%rd21, %rd21, 1;
	add.s64 	%rd20, %rd20, %rd5;
	setp.lt.s64 	%p2, %rd20, %rd2;
	@%p2 bra 	LBB1_2;
LBB1_3:
	{ // callseq 6, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd13;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd21;
	.param .b64 retval0;
	call.uni (retval0), 
	agg_sum_shared, 
	(
	param0, 
	param1
	);
	ld.param.b64 	%rd16, [retval0+0];
	} // callseq 6
	{ // callseq 7, 0
	.reg .b32 temp_param_reg;
	call.uni 
	sync_threadblock, 
	(
	);
	} // callseq 7
	ld.u64 	%rd18, [%rd11];
	mov.u32 	%r8, 0;
	{ // callseq 8, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd13;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd18;
	.param .b32 param2;
	st.param.b32 	[param2+0], %r8;
	call.uni 
	write_back_non_grouped_agg, 
	(
	param0, 
	param1, 
	param2
	);
	} // callseq 8
	ret;

}


[New Thread 0x7fff897fe700 (LWP 32061)]
[Thread 0x7fff897fe700 (LWP 32061) exited]
End of PTXPTX for the GPU:
//
// Generated by LLVM NVPTX Back-End
//

.version 6.3
.target sm_75
.address_size 64

	// .globl	multifrag_query_hoisted_literals
.extern .func  (.param .b32 func_retval0) pos_start_impl
(
	.param .b64 pos_start_impl_param_0
)
;
.extern .func  (.param .b32 func_retval0) group_buff_idx_impl
()
;
.extern .func  (.param .b32 func_retval0) pos_step_impl
()
;
.extern .func  (.param .b64 func_retval0) init_shared_mem_nop
(
	.param .b64 init_shared_mem_nop_param_0,
	.param .b32 init_shared_mem_nop_param_1
)
;
.extern .func write_back_nop
(
	.param .b64 write_back_nop_param_0,
	.param .b64 write_back_nop_param_1,
	.param .b32 write_back_nop_param_2
)
;
.extern .func agg_id_double_shared
(
	.param .b64 agg_id_double_shared_param_0,
	.param .b64 agg_id_double_shared_param_1
)
;
.extern .func sync_warp_protected
(
	.param .b64 sync_warp_protected_param_0,
	.param .b64 sync_warp_protected_param_1
)
;
.extern .func  (.param .b64 func_retval0) asin
(
	.param .b64 asin_param_0
)
;
.visible .func query_group_by_template
(
	.param .b64 query_group_by_template_param_0,
	.param .b64 query_group_by_template_param_1,
	.param .b64 query_group_by_template_param_2,
	.param .b64 query_group_by_template_param_3,
	.param .b64 query_group_by_template_param_4,
	.param .b64 query_group_by_template_param_5,
	.param .b64 query_group_by_template_param_6,
	.param .b32 query_group_by_template_param_7,
	.param .b64 query_group_by_template_param_8,
	.param .b64 query_group_by_template_param_9,
	.param .b64 query_group_by_template_param_10
)
;
.weak .global .align 8 .u64 _ZN08NumbaEnv13$3cdynamic$3e16$3clambda$3e$242Ed;

.visible .entry multifrag_query_hoisted_literals(
	.param .u64 multifrag_query_hoisted_literals_param_0,
	.param .u64 multifrag_query_hoisted_literals_param_1,
	.param .u64 multifrag_query_hoisted_literals_param_2,
	.param .u64 multifrag_query_hoisted_literals_param_3,
	.param .u64 multifrag_query_hoisted_literals_param_4,
	.param .u64 multifrag_query_hoisted_literals_param_5,
	.param .u64 multifrag_query_hoisted_literals_param_6,
	.param .u64 multifrag_query_hoisted_literals_param_7,
	.param .u64 multifrag_query_hoisted_literals_param_8,
	.param .u64 multifrag_query_hoisted_literals_param_9,
	.param .u64 multifrag_query_hoisted_literals_param_10,
	.param .u64 multifrag_query_hoisted_literals_param_11
)
{
	.reg .pred 	%p<5>;
	.reg .b32 	%r<15>;
	.reg .b64 	%rd<36>;

	ld.param.u64 	%rd17, [multifrag_query_hoisted_literals_param_1];
	cvta.to.global.u64 	%rd2, %rd17;
	ld.global.u64 	%rd18, [%rd2];
	setp.eq.s64 	%p1, %rd18, 0;
	@%p1 bra 	LBB0_6;
	ld.param.u64 	%rd14, [multifrag_query_hoisted_literals_param_11];
	ld.param.u64 	%rd13, [multifrag_query_hoisted_literals_param_9];
	ld.param.u64 	%rd12, [multifrag_query_hoisted_literals_param_8];
	ld.param.u64 	%rd11, [multifrag_query_hoisted_literals_param_7];
	ld.param.u64 	%rd10, [multifrag_query_hoisted_literals_param_6];
	ld.param.u64 	%rd9, [multifrag_query_hoisted_literals_param_5];
	ld.param.u64 	%rd8, [multifrag_query_hoisted_literals_param_4];
	ld.param.u64 	%rd7, [multifrag_query_hoisted_literals_param_3];
	ld.param.u64 	%rd6, [multifrag_query_hoisted_literals_param_2];
	ld.param.u64 	%rd15, [multifrag_query_hoisted_literals_param_0];
	ld.param.u64 	%rd16, [multifrag_query_hoisted_literals_param_10];
	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd3, %rd15;
	mov.u64 	%rd35, 0;
	cvta.to.global.u64 	%rd20, %rd35;
	setp.eq.s64 	%p2, %rd3, %rd20;
	@%p2 bra 	LBB0_4;
	mov.u32 	%r14, 1;
LBB0_3:
	add.s32 	%r6, %r14, -1;
	shl.b64 	%rd22, %rd35, 3;
	add.s64 	%rd23, %rd3, %rd22;
	ld.global.u64 	%rd24, [%rd23];
	ld.global.u32 	%r7, [%rd1];
	mul.lo.s32 	%r8, %r7, %r6;
	mul.wide.u32 	%rd25, %r8, 8;
	add.s64 	%rd26, %rd7, %rd25;
	add.s64 	%rd27, %rd8, %rd25;
	{ // callseq 9, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd24;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd6;
	.param .b64 param2;
	st.param.b64 	[param2+0], %rd26;
	.param .b64 param3;
	st.param.b64 	[param3+0], %rd27;
	.param .b64 param4;
	st.param.b64 	[param4+0], %rd9;
	.param .b64 param5;
	st.param.b64 	[param5+0], %rd11;
	.param .b64 param6;
	st.param.b64 	[param6+0], %rd12;
	.param .b32 param7;
	st.param.b32 	[param7+0], %r6;
	.param .b64 param8;
	st.param.b64 	[param8+0], %rd14;
	.param .b64 param9;
	st.param.b64 	[param9+0], %rd10;
	.param .b64 param10;
	st.param.b64 	[param10+0], %rd13;
	call.uni 
	query_group_by_template, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6, 
	param7, 
	param8, 
	param9, 
	param10
	);
	} // callseq 9
	cvt.u64.u32 	%rd35, %r14;
	ld.global.u64 	%rd28, [%rd2];
	setp.gt.u64 	%p3, %rd28, %rd35;
	add.s32 	%r14, %r14, 1;
	@%p3 bra 	LBB0_3;
	bra.uni 	LBB0_6;
LBB0_4:
	mov.u32 	%r13, 1;
	mov.u64 	%rd32, 0;
LBB0_5:
	add.s32 	%r10, %r13, -1;
	ld.global.u32 	%r11, [%rd1];
	mul.lo.s32 	%r12, %r11, %r10;
	mul.wide.u32 	%rd29, %r12, 8;
	add.s64 	%rd30, %rd7, %rd29;
	add.s64 	%rd31, %rd8, %rd29;
	{ // callseq 10, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd32;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd6;
	.param .b64 param2;
	st.param.b64 	[param2+0], %rd30;
	.param .b64 param3;
	st.param.b64 	[param3+0], %rd31;
	.param .b64 param4;
	st.param.b64 	[param4+0], %rd9;
	.param .b64 param5;
	st.param.b64 	[param5+0], %rd11;
	.param .b64 param6;
	st.param.b64 	[param6+0], %rd12;
	.param .b32 param7;
	st.param.b32 	[param7+0], %r10;
	.param .b64 param8;
	st.param.b64 	[param8+0], %rd14;
	.param .b64 param9;
	st.param.b64 	[param9+0], %rd10;
	.param .b64 param10;
	st.param.b64 	[param10+0], %rd13;
	call.uni 
	query_group_by_template, 
	(
	param0, 
	param1, 
	param2, 
	param3, 
	param4, 
	param5, 
	param6, 
	param7, 
	param8, 
	param9, 
	param10
	);
	} // callseq 10
	cvt.u64.u32 	%rd33, %r13;
	ld.global.u64 	%rd34, [%rd2];
	setp.gt.u64 	%p4, %rd34, %rd33;
	add.s32 	%r13, %r13, 1;
	@%p4 bra 	LBB0_5;
LBB0_6:
	ret;

}
	// .globl	arcsin__0
.visible .func  (.param .b64 func_retval0) arcsin__0(
	.param .b64 arcsin__0_param_0
)
{
	.reg .f64 	%fd<4>;

	ld.param.f64 	%fd1, [arcsin__0_param_0];
	{ // callseq 11, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.f64 	[param0+0], %fd1;
	.param .b64 retval0;
	call.uni (retval0), 
	asin, 
	(
	param0
	);
	ld.param.f64 	%fd2, [retval0+0];
	} // callseq 11
	st.param.f64 	[func_retval0+0], %fd2;
	ret;

}
	// .globl	query_group_by_template
.visible .func query_group_by_template(
	.param .b64 query_group_by_template_param_0,
	.param .b64 query_group_by_template_param_1,
	.param .b64 query_group_by_template_param_2,
	.param .b64 query_group_by_template_param_3,
	.param .b64 query_group_by_template_param_4,
	.param .b64 query_group_by_template_param_5,
	.param .b64 query_group_by_template_param_6,
	.param .b32 query_group_by_template_param_7,
	.param .b64 query_group_by_template_param_8,
	.param .b64 query_group_by_template_param_9,
	.param .b64 query_group_by_template_param_10
)
{
	.reg .pred 	%p<11>;
	.reg .b32 	%r<26>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<38>;

	ld.param.u64 	%rd17, [query_group_by_template_param_10];
	ld.param.u64 	%rd18, [query_group_by_template_param_0];
	ld.u64 	%rd1, [%rd18];
	ld.param.u64 	%rd19, [query_group_by_template_param_2];
	ld.u64 	%rd2, [%rd19];
	ld.param.u64 	%rd20, [query_group_by_template_param_4];
	ld.u32 	%r1, [%rd20];
	{ // callseq 12, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd17;
	.param .b32 retval0;
	call.uni (retval0), 
	pos_start_impl, 
	(
	param0
	);
	ld.param.b32 	%r7, [retval0+0];
	} // callseq 12
	{ // callseq 13, 0
	.reg .b32 temp_param_reg;
	.param .b32 retval0;
	call.uni (retval0), 
	group_buff_idx_impl, 
	(
	);
	ld.param.b32 	%r9, [retval0+0];
	} // callseq 13
	cvt.s64.s32 	%rd36, %r7;
	ld.param.u64 	%rd21, [query_group_by_template_param_6];
	mul.wide.s32 	%rd22, %r9, 8;
	add.s64 	%rd23, %rd21, %rd22;
	ld.u64 	%rd4, [%rd23];
	mov.u32 	%r11, 0;
	{ // callseq 14, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd4;
	.param .b32 param1;
	st.param.b32 	[param1+0], %r11;
	.param .b64 retval0;
	call.uni (retval0), 
	init_shared_mem_nop, 
	(
	param0, 
	param1
	);
	ld.param.b64 	%rd24, [retval0+0];
	} // callseq 14
	setp.le.s64 	%p1, %rd2, %rd36;
	@%p1 bra 	LBB2_14;
	ld.param.u64 	%rd16, [query_group_by_template_param_9];
	cvt.u32.u64 	%r12, %rd36;
	{ // callseq 15, 0
	.reg .b32 temp_param_reg;
	.param .b32 retval0;
	call.uni (retval0), 
	pos_step_impl, 
	(
	);
	ld.param.b32 	%r13, [retval0+0];
	} // callseq 15
	cvt.s64.s32 	%rd6, %r13;
	neg.s32 	%r24, %r12;
	shl.b64 	%rd25, %rd36, 3;
	add.s64 	%rd35, %rd1, %rd25;
	mul.wide.s32 	%rd8, %r13, 8;
	mov.f64 	%fd4, 0d0010000000000000;
LBB2_2:
	atom.add.u32 	%r4, [%rd16], 1;
	setp.gt.u32 	%p2, %r4, 4;
	mov.u64 	%rd37, 0;
	@%p2 bra 	LBB2_4;
	mul.wide.u32 	%rd27, %r4, 24;
	add.s64 	%rd11, %rd4, %rd27;
	add.s64 	%rd37, %rd11, 8;
	st.u64 	[%rd11], %rd36;
LBB2_4:
	setp.eq.s64 	%p3, %rd37, 0;
	mov.u32 	%r25, %r24;
	@%p3 bra 	LBB2_8;
	ld.f64 	%fd1, [%rd35];
	{ // callseq 16, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd37;
	.param .b64 param1;
	st.param.f64 	[param1+0], %fd1;
	call.uni 
	agg_id_double_shared, 
	(
	param0, 
	param1
	);
	} // callseq 16
	setp.eq.f64 	%p4, %fd1, 0d0010000000000000;
	mov.f64 	%fd6, %fd4;
	@%p4 bra 	LBB2_7;
	{ // callseq 17, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.f64 	[param0+0], %fd1;
	.param .b64 retval0;
	call.uni (retval0), 
	arcsin__0, 
	(
	param0
	);
	ld.param.f64 	%fd6, [retval0+0];
	} // callseq 17
LBB2_7:
	add.s64 	%rd28, %rd37, 8;
	{ // callseq 18, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd28;
	.param .b64 param1;
	st.param.f64 	[param1+0], %fd6;
	call.uni 
	agg_id_double_shared, 
	(
	param0, 
	param1
	);
	} // callseq 18
	mov.u32 	%r25, %r11;
LBB2_8:
	setp.eq.s32 	%p5, %r25, 0;
	@%p5 bra 	LBB2_11;
	mov.u64 	%rd29, 0;
	{ // callseq 19, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd29;
	.param .b32 retval0;
	call.uni (retval0), 
	pos_start_impl, 
	(
	param0
	);
	ld.param.b32 	%r16, [retval0+0];
	} // callseq 19
	mul.wide.s32 	%rd30, %r16, 4;
	add.s64 	%rd31, %rd17, %rd30;
	ld.u32 	%r18, [%rd31];
	setp.gt.s32 	%p6, %r18, 0;
	@%p6 bra 	LBB2_11;
	{ // callseq 20, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd29;
	.param .b32 retval0;
	call.uni (retval0), 
	pos_start_impl, 
	(
	param0
	);
	ld.param.b32 	%r19, [retval0+0];
	} // callseq 20
	mul.wide.s32 	%rd33, %r19, 4;
	add.s64 	%rd34, %rd17, %rd33;
	st.u32 	[%rd34], %r25;
LBB2_11:
	setp.ne.s32 	%p7, %r25, 9;
	@%p7 bra 	LBB2_13;
	bra.uni 	LBB2_12;
LBB2_13:
	{ // callseq 21, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd36;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd2;
	call.uni 
	sync_warp_protected, 
	(
	param0, 
	param1
	);
	} // callseq 21
	add.s64 	%rd36, %rd36, %rd6;
	setp.lt.s64 	%p8, %rd36, %rd2;
	cvt.u32.u64 	%r21, %rd6;
	add.s32 	%r22, %r4, 1;
	setp.lt.s32 	%p9, %r22, %r1;
	and.pred  	%p10, %p8, %p9;
	sub.s32 	%r24, %r24, %r21;
	add.s64 	%rd35, %rd35, %rd8;
	@%p10 bra 	LBB2_2;
LBB2_14:
	{ // callseq 22, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd4;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd24;
	.param .b32 param2;
	st.param.b32 	[param2+0], %r11;
	call.uni 
	write_back_nop, 
	(
	param0, 
	param1, 
	param2
	);
	} // callseq 22
	ret;
LBB2_12:
	ret;

}

warning: Cuda API error detected: cuLinkComplete returned (0x3e7)

'''

</details>

**Comment by pearu** [comment]
```
$ llc -mcpu=sm_75 cuda_llvm_ir.ll -o cuda_llvm_ir.ptx
$ ptxas -arch=sm_75 -m64 --opt-level=0 cuda_llvm_ir.ptx -o cuda_llvm_ir.cubin
ptxas fatal   : Unresolved extern function 'pos_start_impl'
```

**Comment by pearu** [comment]
With https://github.com/omnisci/omniscidb-internal/pull/4714, we have improved error message:
```
2020-08-10T16:18:00.059731 F 26317 10 NvidiaKernel.cpp:132 Check failed: cuLinkComplete(link_state, &cubin, &cubinSize) == CUDA_SUCCESS (999 == 0) error   : Undefined reference to 'asin' in 'Input 2'
Aborted (core dumped)
```
